# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 110, 220, 30))
        self.label.setStyleSheet("font: 12pt \"微軟正黑體\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.helloButton = QtWidgets.QPushButton(Dialog)
        self.helloButton.setGeometry(QtCore.QRect(110, 190, 60, 31))
        self.helloButton.setObjectName("helloButton")
        self.Test = QtWidgets.QPushButton(Dialog)
        self.Test.setGeometry(QtCore.QRect(240, 190, 60, 31))
        self.Test.setObjectName("Test")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 150, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pic = QtWidgets.QLabel(Dialog)
        self.pic.setGeometry(QtCore.QRect(160, 30, 81, 71))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("s.jpg"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "hihi"))
        self.label.setText(_translate("Dialog", "please enter value"))
        self.helloButton.setText(_translate("Dialog", "Hello"))
        self.Test.setText(_translate("Dialog", "hihi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
