# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 210, 56, 17))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(90, 160, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 160, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 78, 71, 31))
        self.label.setObjectName("label")
        self.pic2 = QtWidgets.QLabel(Dialog)
        self.pic2.setGeometry(QtCore.QRect(20, 30, 111, 'tCo2 90,)
      ,rbel")
        self.pic2 = QtWidgets.QLabel(Dialog)
        e        Dia2.setGeometry(QtC Tpel  e   e      b(y(QtCore.Qa2.setGete O     metp   eelf.pic2 = QtWidg            p      e1          egC.esD.eabel")
        self.pic2 = Qtf.pic2 = QtWidg          (opO         e   e   ei      .se         eoQtWidg          (opO       tWidg          (5.,5unea0folMid Ma'm3 p      e1          egC.esD.eabel")
 3      self.pic2 = Qtf.pic2 =3QtWidg          (opO         4   e   ei      .se         eoQtWidg          (opO       tWid4          (5.,5unea0folMid Ma'm5 p      e1          egC.esD.eabel")
 4      self.pic2 = Qtf.pic2 =4QtWi         egC.esD  (ansl